/**
 * The asset registry: `credits.json`.
 *
 * One file names every asset this repository ships, who made it, where it came
 * from and under what licence — and, for a texture, which class it is, because
 * the licence and the encoder settings are two facts about the same asset and
 * splitting them across two files is how they drift apart.
 *
 * `CREDITS.md` and `packages/client/public/credits.json` are *generated* from
 * it, so the human-readable credits and the machine-readable ones cannot
 * disagree. `pnpm assets:build --check` fails when either is stale.
 *
 * The licence rules are in here rather than in a document because a document
 * cannot fail a build. Three of them are worth knowing before you add an entry:
 *
 *   - **Content is CC0 or it does not ship.** Not "CC-BY with attribution" —
 *     attribution obligations are a thing you have to keep honouring, and this
 *     project would rather not have that class of obligation at all.
 *   - **OpenGameArt and Freesound are mixed-licence.** A search result there is
 *     not a licence; the per-item licence is, and it has to say CC0.
 *   - **Mixamo is a trap.** Its licence permits using the animations and
 *     forbids redistributing the raw asset files, which is exactly what
 *     committing one to a public repository does.
 */

/** What a texture is *for*, which is what decides how it is compressed. */
export const TEXTURE_CLASSES = ['albedo', 'normal', 'srgb', 'linear'] as const
export type TextureClass = (typeof TEXTURE_CLASSES)[number]

/**
 * What kind of thing an entry covers.
 *
 * `vendored` is code, not content: the KTX2 transcoders and the meshopt decoder
 * that we serve from our own origin rather than someone else's CDN. It is the
 * one kind allowed a licence other than CC0.
 *
 * `audio` has no build step here — `pnpm audio:bake` synthesises the WAVs from
 * `tools/synth-audio.ts` and writes them straight into `public/audio/`. It is
 * in the registry anyway, because "which licence is that sound under" is one
 * question and it should have one answer.
 */
export const ASSET_KINDS = ['texture', 'model', 'audio', 'vendored'] as const
export type AssetKind = (typeof ASSET_KINDS)[number]

export type CreditEntry = {
  /** Stable identifier. Appears in the credits screen's DOM, not to the player. */
  readonly id: string
  readonly title: string
  readonly author: string
  /** Where it came from. A URL, always — "made by us" points at this repository. */
  readonly source: string
  /** SPDX identifier. */
  readonly licence: string
  readonly kind: AssetKind
  /** Repo-relative POSIX paths this entry covers. Non-empty. */
  readonly files: readonly string[]
  /** Required on `texture` entries, forbidden on every other kind. */
  readonly textureClass?: TextureClass
  /** Anything a reader would otherwise have to ask about. */
  readonly note?: string
}

export type Credits = {
  readonly entries: readonly CreditEntry[]
}

/**
 * Licences content may carry: exactly one.
 *
 * CC0 is a dedication to the public domain, so there is no attribution to keep
 * honouring, no share-alike to propagate and no notice file to maintain. The
 * credits in this repository are courtesy, not compliance, which is the only
 * reason they can be generated by a script without a lawyer reading the output.
 */
export const CONTENT_LICENCES = ['CC0-1.0'] as const

/** Licences vendored code may carry. Permissive, notice-only, all of them. */
export const VENDORED_LICENCES = ['Apache-2.0', 'MIT', 'BSD-3-Clause', 'CC0-1.0'] as const

/**
 * Hosts whose per-item licences vary, so a link to one proves nothing on its
 * own. Allowed, but only with a CC0 licence recorded beside it — which the
 * content rule already requires, so this exists to put the *reason* in the
 * error message rather than leaving someone to rediscover it.
 */
export const MIXED_LICENCE_HOSTS = ['opengameart.org', 'freesound.org'] as const

/** Hosts nothing may be sourced from, and why. */
export const FORBIDDEN_HOSTS: ReadonlyArray<readonly [host: string, reason: string]> = [
  [
    'mixamo.com',
    'the Mixamo licence permits using the animations and forbids redistributing the raw asset files, which is what committing one to a public repository does',
  ],
]

/* --------------------------------------------------------------------------
 * Parsing and validation
 *
 * `credits.json` is authored by hand, so every failure here has to say what to
 * write instead. A validator that only says "invalid" makes the author guess.
 * ----------------------------------------------------------------------- */

function fail(message: string): never {
  throw new Error(`gladiator: credits.json — ${message}`)
}

function hostOf(url: string): string | null {
  try {
    return new URL(url).hostname.replace(/^www\./, '')
  } catch {
    return null
  }
}

function asString(value: unknown, where: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    fail(`${where} must be a non-empty string`)
  }
  return value
}

function parseEntry(raw: unknown, index: number): CreditEntry {
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) {
    fail(`entries[${index}] must be an object`)
  }
  const record = raw as Record<string, unknown>
  const where = `entries[${index}]`

  const id = asString(record['id'], `${where}.id`)
  const kindValue = asString(record['kind'], `${where}.kind`)
  if (!(ASSET_KINDS as readonly string[]).includes(kindValue)) {
    fail(`${where}.kind is ${JSON.stringify(kindValue)} — expected one of ${ASSET_KINDS.join(', ')}`)
  }
  const kind = kindValue as AssetKind

  const files = record['files']
  if (!Array.isArray(files) || files.length === 0) {
    fail(`${where}.files must be a non-empty array of repo-relative paths`)
  }
  const paths = files.map((file, n) => asString(file, `${where}.files[${n}]`))
  for (const path of paths) {
    if (path.startsWith('/') || path.includes('\\') || path.includes('..')) {
      fail(`${where}.files contains ${JSON.stringify(path)} — paths are repo-relative and POSIX`)
    }
  }

  const textureClassValue = record['textureClass']
  if (kind === 'texture') {
    const value = asString(textureClassValue, `${where}.textureClass`)
    if (!(TEXTURE_CLASSES as readonly string[]).includes(value)) {
      fail(
        `${where}.textureClass is ${JSON.stringify(value)} — expected one of ${TEXTURE_CLASSES.join(', ')}`,
      )
    }
  } else if (textureClassValue !== undefined) {
    fail(`${where}.textureClass is only meaningful on a texture entry (this one is ${kind})`)
  }

  const note = record['note']
  if (note !== undefined && typeof note !== 'string') fail(`${where}.note must be a string`)

  return {
    id,
    title: asString(record['title'], `${where}.title`),
    author: asString(record['author'], `${where}.author`),
    source: asString(record['source'], `${where}.source`),
    licence: asString(record['licence'], `${where}.licence`),
    kind,
    files: paths,
    ...(kind === 'texture' ? { textureClass: textureClassValue as TextureClass } : {}),
    ...(typeof note === 'string' ? { note } : {}),
  }
}

/** Everything that is wrong with a registry, rather than the first thing. */
export function validateCredits(credits: Credits): string[] {
  const problems: string[] = []
  const seenIds = new Set<string>()
  const seenFiles = new Map<string, string>()

  for (const entry of credits.entries) {
    if (seenIds.has(entry.id)) problems.push(`duplicate id ${JSON.stringify(entry.id)}`)
    seenIds.add(entry.id)

    for (const file of entry.files) {
      const owner = seenFiles.get(file)
      if (owner !== undefined) {
        problems.push(`${file} is claimed by both ${owner} and ${entry.id}`)
      }
      seenFiles.set(file, entry.id)
    }

    const allowed: readonly string[] =
      entry.kind === 'vendored' ? VENDORED_LICENCES : CONTENT_LICENCES
    if (!allowed.includes(entry.licence)) {
      problems.push(
        entry.kind === 'vendored'
          ? `${entry.id} is ${entry.licence}; vendored code may be one of ${VENDORED_LICENCES.join(', ')}`
          : `${entry.id} is ${entry.licence}; content ships under ${CONTENT_LICENCES.join(', ')} only — an attribution or share-alike obligation is one this project does not take on`,
      )
    }

    const host = hostOf(entry.source)
    if (host === null) {
      problems.push(`${entry.id} has a source that is not a URL: ${JSON.stringify(entry.source)}`)
      continue
    }
    for (const [forbidden, reason] of FORBIDDEN_HOSTS) {
      if (host === forbidden || host.endsWith(`.${forbidden}`)) {
        problems.push(`${entry.id} is sourced from ${forbidden}, which nothing may be — ${reason}`)
      }
    }
    if (
      (MIXED_LICENCE_HOSTS as readonly string[]).includes(host) &&
      entry.licence !== 'CC0-1.0'
    ) {
      problems.push(
        `${entry.id} comes from ${host}, where the licence varies per item — record the item's own licence, and it has to be CC0-1.0`,
      )
    }
  }

  return problems
}

/** Parse and validate. Throws on the first structural problem, lists the rest. */
export function parseCredits(text: string): Credits {
  let raw: unknown
  try {
    raw = JSON.parse(text)
  } catch (error) {
    fail(`is not valid JSON — ${(error as Error).message}`)
  }
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) {
    fail('must be an object with an "entries" array')
  }
  const entries = (raw as Record<string, unknown>)['entries']
  if (!Array.isArray(entries)) fail('must have an "entries" array')

  const credits: Credits = { entries: entries.map(parseEntry) }
  const problems = validateCredits(credits)
  if (problems.length > 0) {
    fail(`\n  - ${problems.join('\n  - ')}`)
  }
  return credits
}

/* --------------------------------------------------------------------------
 * Rendering
 * ----------------------------------------------------------------------- */

const KIND_HEADINGS: ReadonlyArray<readonly [AssetKind, string]> = [
  ['model', 'Models'],
  ['texture', 'Textures'],
  ['audio', 'Audio'],
  ['vendored', 'Vendored code'],
]

/**
 * Where a licence can be read.
 *
 * A row that names `CC0-1.0` and nothing else is a row that assumes the reader
 * knows what that means and where to check. `tools/audio-assets.test.ts`
 * requires the URL, and it is right to.
 */
const LICENCE_URLS: Readonly<Record<string, string>> = {
  'CC0-1.0': 'https://creativecommons.org/publicdomain/zero/1.0/',
  'Apache-2.0': 'https://www.apache.org/licenses/LICENSE-2.0',
  MIT: 'https://opensource.org/license/mit',
  'BSD-3-Clause': 'https://opensource.org/license/bsd-3-clause',
}

const CREDITS_PREAMBLE = `<!--
  Generated by \`pnpm assets:build\` from credits.json. Do not edit by hand —
  \`pnpm assets:build --check\` fails when this file and the registry disagree,
  and when a committed asset has no entry at all.
-->

# Credits

Every asset that ships in Gladiator, where it came from, and under what licence.

One row per file, and the rule is that the row exists **before** the file does.
\`pnpm assets:build --check\` fails on any committed file under \`assets/\` or
\`packages/client/public/\` that no entry accounts for, and on any entry naming a
file that is not committed — so this is a gate rather than a good intention.

> **Mixamo, and things like it, are a trap.** Free with an account is not the
> same as redistributable: Mixamo's licence permits *use* of its animations and
> characters and does not permit redistributing the raw asset files, so
> committing one to a public repository is a violation however the game uses it.
> The same applies to most "free" sample packs whose licence is a sentence on a
> download page. If the licence cannot be quoted in this file, the asset cannot
> be in this repository. The validator rejects a Mixamo source by hostname, and
> rejects any content licence that is not CC0.

Content is [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) — a
public-domain dedication, so nothing here carries an attribution or share-alike
obligation, and these credits are courtesy. The vendored code below is someone
else's work under a permissive licence, and that licence *is* an obligation:
its notice ships beside the file.

The pipeline that produces the shipped form of all of this is
[\`docs/assets.md\`](./docs/assets.md); the sounds are
[\`docs/audio.md\`](./docs/audio.md).
`

const CREDITS_CODA = `
## Code

Gladiator's movement is a port of the \`bg_pmove.c\` from Quake III Arena
(id Software, GPL-2.0-or-later). What was taken is the *algorithm* — the order
of operations, the acceleration gate, the velocity snapping — reimplemented in
TypeScript from the published source and the behaviour it produces, with the
constants and their reasoning written down in
[\`docs/physics-spec.md\`](./docs/physics-spec.md). No id Software code, asset,
map or sound is redistributed here.
`

function licenceCell(licence: string): string {
  const url = LICENCE_URLS[licence]
  return url === undefined ? licence : `[${licence}](${url})`
}

/**
 * `CREDITS.md`, exactly as it goes on disk.
 *
 * `derived` is what the pipeline produces from each entry — the `.ktx2` a `.png`
 * becomes, the `.gltf` and `.bin` a model becomes. Those are committed files
 * too, so they get their own rows: "every asset in the tree has a row naming
 * where it came from" is only true if the compressed ones do.
 */
export function renderCreditsMarkdown(
  credits: Credits,
  derived: ReadonlyMap<string, readonly string[]> = new Map(),
): string {
  const lines: string[] = [CREDITS_PREAMBLE]

  for (const [kind, heading] of KIND_HEADINGS) {
    const entries = credits.entries.filter((entry) => entry.kind === kind)
    if (entries.length === 0) continue

    lines.push(`\n---\n`)
    lines.push(`## ${heading}\n`)
    lines.push('| File | What it is | Author | Source | Licence |')
    lines.push('| ---- | ---------- | ------ | ------ | ------- |')
    for (const entry of entries) {
      const what = entry.note === undefined ? entry.title : `${entry.title} — ${entry.note}`
      const row = (file: string, description: string) =>
        `| \`${file}\` | ${description} | ${entry.author} | <${entry.source}> | ${licenceCell(entry.licence)} |`

      // One row per *file*, not per entry: "where did that file come from" is
      // the question this table is read to answer, and a row covering four
      // files answers it once, for whoever thinks to look at the right one.
      for (const file of entry.files) lines.push(row(file, what))
      for (const output of derived.get(entry.id) ?? []) {
        lines.push(row(output, `${entry.title} — compressed by \`pnpm assets:build\``))
      }
    }
    lines.push('')
  }

  lines.push(`\n---\n${CREDITS_CODA}`)

  return `${lines.join('\n').trimEnd()}\n`
}

/**
 * The machine-readable credits the client fetches, served at `/credits.json`.
 *
 * A trimmed copy: the build fields — which class a texture is, which files an
 * entry covers — are facts about the pipeline, and a player reading the credits
 * screen is not asking about the pipeline.
 */
export function renderPublicCredits(credits: Credits): string {
  const payload = {
    entries: credits.entries.map((entry) => ({
      id: entry.id,
      title: entry.title,
      author: entry.author,
      source: entry.source,
      licence: entry.licence,
      kind: entry.kind,
    })),
  }
  return `${JSON.stringify(payload, null, 2)}\n`
}
