/**
 * `pnpm assets:placeholders` — write the authored sources under `assets/`.
 *
 * This is where Blender goes, eventually. Until there is art, the sources are
 * generated by this program, and that is not only a convenience: an asset a
 * program in this repository wrote is an asset whose provenance is not a claim.
 * It is CC0 because there is nothing in it that came from anywhere else, and
 * anyone can check that by reading this file.
 *
 * It is a *source* generator, not a build step. What it writes is committed and
 * then compressed by `pnpm assets:build`, exactly as a real export would be. So
 * the day someone drops a real `.gltf` and its `.png` files into `assets/`,
 * nothing downstream changes and this file stops being run.
 *
 * Everything here is deterministic — a fixed lattice and a fixed LCG, no clock
 * and no `Math.random` — so re-running it produces byte-identical sources and
 * the committed artifacts do not churn.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import { Document, Format, NodeIO } from '@gltf-transform/core'
import { PNG } from 'pngjs'

import { abs } from './assets/plan.ts'

const SIZE = 256

/* --------------------------------------------------------------------------
 * A height field, and the three maps that come off it
 *
 * One field, three textures, because that is how a real material is authored:
 * the albedo, the normal and the mask are all descriptions of the same surface,
 * and generating them independently would produce three surfaces that do not
 * agree with each other.
 * ----------------------------------------------------------------------- */

/** Deterministic value noise: a fixed lattice, hashed, bilinearly interpolated. */
function hash2(x: number, y: number): number {
  let h = (x * 374761393 + y * 668265263) | 0
  h = (h ^ (h >>> 13)) * 1274126177
  return ((h ^ (h >>> 16)) >>> 0) / 4294967295
}

function smoothstep(t: number): number {
  return t * t * (3 - 2 * t)
}

function noise(x: number, y: number, cells: number): number {
  const sx = (x / SIZE) * cells
  const sy = (y / SIZE) * cells
  const x0 = Math.floor(sx)
  const y0 = Math.floor(sy)
  const fx = smoothstep(sx - x0)
  const fy = smoothstep(sy - y0)
  const a = hash2(x0, y0)
  const b = hash2(x0 + 1, y0)
  const c = hash2(x0, y0 + 1)
  const d = hash2(x0 + 1, y0 + 1)
  return (a + (b - a) * fx) * (1 - fy) + (c + (d - c) * fx) * fy
}

/** Distance to the nearest plate seam, in texels. Plates are 64 texels across. */
function seamDistance(x: number, y: number): number {
  const px = Math.min(x % 64, 63 - (x % 64))
  const py = Math.min(y % 64, 63 - (y % 64))
  return Math.min(px, py)
}

/** Distance to the nearest rivet centre, in texels. One rivet per plate corner. */
function rivetDistance(x: number, y: number): number {
  const cx = Math.abs((x % 64) - 10)
  const cy = Math.abs((y % 64) - 10)
  return Math.sqrt(cx * cx + cy * cy)
}

/** The surface, in [0, 1]: plates raised, seams cut, rivets domed. */
function height(x: number, y: number): number {
  const seam = Math.min(1, seamDistance(x, y) / 3)
  const rivet = Math.max(0, 1 - rivetDistance(x, y) / 4)
  const grain = noise(x, y, 32) * 0.06 + noise(x, y, 8) * 0.04
  return Math.min(1, 0.35 + seam * 0.4 + rivet * 0.35 + grain)
}

function writePng(path: string, fill: (x: number, y: number) => readonly number[]): void {
  const png = new PNG({ width: SIZE, height: SIZE })
  for (let y = 0; y < SIZE; y++) {
    for (let x = 0; x < SIZE; x++) {
      const [r, g, b, a] = fill(x, y) as [number, number, number, number?]
      const i = (y * SIZE + x) * 4
      png.data[i] = r
      png.data[i + 1] = g
      png.data[i + 2] = b
      png.data[i + 3] = a ?? 255
    }
  }
  const bytes = PNG.sync.write(png)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, bytes)
  return
}

const clamp255 = (value: number): number => Math.max(0, Math.min(255, Math.round(value)))

function albedo(x: number, y: number): readonly number[] {
  const h = height(x, y)
  const rust = Math.max(0, noise(x, y, 6) - 0.55) * 2.2
  const steel = 40 + h * 90
  return [
    clamp255(steel + rust * 90),
    clamp255(steel + rust * 34),
    clamp255(steel * 1.05 + rust * 4),
  ]
}

/**
 * A tangent-space normal, by central differences on the height field.
 *
 * `+y` is up in the texture, which is glTF's convention and OpenGL's. Blender
 * exports the same way. DirectX-style green is the other one, and it is the
 * bug that makes lighting look inverted on exactly half the surfaces.
 */
function normal(x: number, y: number): readonly number[] {
  const scale = 6
  const dx = (height(x + 1, y) - height(x - 1, y)) * scale
  const dy = (height(x, y + 1) - height(x, y - 1)) * scale
  const length = Math.sqrt(dx * dx + dy * dy + 1)
  return [
    clamp255((-dx / length) * 127.5 + 127.5),
    clamp255((-dy / length) * 127.5 + 127.5),
    clamp255((1 / length) * 127.5 + 127.5),
  ]
}

/** Occlusion in red, roughness in green, metalness in blue — the ORM packing. */
function orm(x: number, y: number): readonly number[] {
  const h = height(x, y)
  const rust = Math.max(0, noise(x, y, 6) - 0.55) * 2.2
  return [
    clamp255(120 + h * 135),
    clamp255(90 + (1 - h) * 60 + rust * 90),
    clamp255(255 - rust * 220),
  ]
}

/** A soft bake: one warm key from above, one cool bounce from the floor. */
function lightmap(x: number, y: number): readonly number[] {
  const u = x / (SIZE - 1)
  const v = y / (SIZE - 1)
  const key = Math.max(0, 1 - Math.sqrt((u - 0.35) * (u - 0.35) + (v - 0.25) * (v - 0.25)) * 1.4)
  const bounce = Math.max(0, 1 - Math.sqrt((u - 0.7) * (u - 0.7) + (v - 0.85) * (v - 0.85)) * 1.6)
  return [
    clamp255(30 + key * 200 + bounce * 40),
    clamp255(28 + key * 180 + bounce * 60),
    clamp255(34 + key * 140 + bounce * 110),
  ]
}

/* --------------------------------------------------------------------------
 * The model
 *
 * A crate: 24 vertices, 12 triangles, two UV sets. It exists to be the thing
 * the pipeline carries end to end, and specifically to carry a **second UV
 * set**, because `TEXCOORD_1` surviving compression is the whole reason the
 * lightmap convention is worth pinning.
 * ----------------------------------------------------------------------- */

/** Half-extent, in Quake units: a crate a player can step on to but not over. */
const HALF = 16

type Face = {
  readonly normal: readonly [number, number, number]
  readonly corners: ReadonlyArray<readonly [number, number, number]>
}

const FACES: readonly Face[] = [
  {
    normal: [1, 0, 0],
    corners: [
      [1, -1, -1],
      [1, 1, -1],
      [1, 1, 1],
      [1, -1, 1],
    ],
  },
  {
    normal: [-1, 0, 0],
    corners: [
      [-1, 1, -1],
      [-1, -1, -1],
      [-1, -1, 1],
      [-1, 1, 1],
    ],
  },
  {
    normal: [0, 1, 0],
    corners: [
      [1, 1, -1],
      [-1, 1, -1],
      [-1, 1, 1],
      [1, 1, 1],
    ],
  },
  {
    normal: [0, -1, 0],
    corners: [
      [-1, -1, -1],
      [1, -1, -1],
      [1, -1, 1],
      [-1, -1, 1],
    ],
  },
  {
    normal: [0, 0, 1],
    corners: [
      [-1, -1, 1],
      [1, -1, 1],
      [1, 1, 1],
      [-1, 1, 1],
    ],
  },
  {
    normal: [0, 0, -1],
    corners: [
      [-1, 1, -1],
      [1, 1, -1],
      [1, -1, -1],
      [-1, -1, -1],
    ],
  },
]

/** The per-face corner UVs, shared by both sets before the atlas offset. */
const CORNER_UV: ReadonlyArray<readonly [number, number]> = [
  [0, 0],
  [1, 0],
  [1, 1],
  [0, 1],
]

function buildCrate(): {
  readonly position: Float32Array
  readonly normal: Float32Array
  readonly uv0: Float32Array
  readonly uv1: Float32Array
  readonly indices: Uint16Array
} {
  const position = new Float32Array(24 * 3)
  const normals = new Float32Array(24 * 3)
  const uv0 = new Float32Array(24 * 2)
  const uv1 = new Float32Array(24 * 2)
  const indices = new Uint16Array(36)

  for (let face = 0; face < FACES.length; face++) {
    const { normal: n, corners } = FACES[face] as Face
    // The lightmap atlas: six faces in a 3x2 grid, with a half-texel gutter so
    // bilinear filtering at a cell edge cannot pull in the neighbour's light.
    const cellX = face % 3
    const cellY = Math.floor(face / 3)
    const gutter = 0.01

    for (let corner = 0; corner < 4; corner++) {
      const vertex = face * 4 + corner
      const [px, py, pz] = corners[corner] as readonly [number, number, number]
      position[vertex * 3] = px * HALF
      position[vertex * 3 + 1] = py * HALF
      position[vertex * 3 + 2] = pz * HALF
      normals[vertex * 3] = n[0]
      normals[vertex * 3 + 1] = n[1]
      normals[vertex * 3 + 2] = n[2]

      const [cu, cv] = CORNER_UV[corner] as readonly [number, number]
      uv0[vertex * 2] = cu
      uv0[vertex * 2 + 1] = cv
      uv1[vertex * 2] = (cellX + gutter + cu * (1 - 2 * gutter)) / 3
      uv1[vertex * 2 + 1] = (cellY + gutter + cv * (1 - 2 * gutter)) / 2
    }

    const base = face * 4
    const slot = face * 6
    indices[slot] = base
    indices[slot + 1] = base + 1
    indices[slot + 2] = base + 2
    indices[slot + 3] = base
    indices[slot + 4] = base + 2
    indices[slot + 5] = base + 3
  }

  return { position, normal: normals, uv0, uv1, indices }
}

async function writeCrate(textures: ReadonlyMap<string, Uint8Array>): Promise<void> {
  const mesh = buildCrate()
  const document = new Document()
  const buffer = document.createBuffer().setURI('crucible_crate.bin')

  const accessor = (type: 'VEC3' | 'VEC2' | 'SCALAR', array: Float32Array | Uint16Array) =>
    document.createAccessor().setType(type).setArray(array).setBuffer(buffer)

  const texture = (name: string, file: string) =>
    document
      .createTexture(name)
      .setMimeType('image/png')
      .setImage(textures.get(file) as Uint8Array)
      .setURI(`../textures/${file}`)

  const material = document
    .createMaterial('crucible_crate')
    .setBaseColorTexture(texture('albedo', 'crucible_crate_albedo.png'))
    .setNormalTexture(texture('normal', 'crucible_crate_normal.png'))
    .setMetallicRoughnessTexture(texture('orm', 'crucible_crate_orm.png'))
    .setRoughnessFactor(1)
    .setMetallicFactor(1)

  const primitive = document
    .createPrimitive()
    .setAttribute('POSITION', accessor('VEC3', mesh.position))
    .setAttribute('NORMAL', accessor('VEC3', mesh.normal))
    .setAttribute('TEXCOORD_0', accessor('VEC2', mesh.uv0))
    .setAttribute('TEXCOORD_1', accessor('VEC2', mesh.uv1))
    .setIndices(accessor('SCALAR', mesh.indices))
    .setMaterial(material)

  document
    .createScene('crucible_crate')
    .addChild(document.createNode('crate').setMesh(document.createMesh('crate').addPrimitive(primitive)))

  const written = await new NodeIO().writeJSON(document, { format: Format.GLTF })
  writeFileSync(abs('assets/models/crucible_crate.gltf'), `${JSON.stringify(written.json, null, 2)}\n`)
  const bin = written.resources['crucible_crate.bin']
  if (bin === undefined) throw new Error('gladiator: the crate produced no buffer')
  writeFileSync(abs('assets/models/crucible_crate.bin'), bin)
}

/* --------------------------------------------------------------------------
 * Entry point
 * ----------------------------------------------------------------------- */

const TEXTURES: ReadonlyArray<readonly [string, (x: number, y: number) => readonly number[]]> = [
  ['crucible_crate_albedo.png', albedo],
  ['crucible_crate_normal.png', normal],
  ['crucible_crate_orm.png', orm],
  ['crucible_lightmap.png', lightmap],
]

mkdirSync(abs('assets/models'), { recursive: true })

const written = new Map<string, Uint8Array>()
for (const [file, fill] of TEXTURES) {
  const path = abs(`assets/textures/${file}`)
  writePng(path, fill)
  process.stdout.write(`  wrote assets/textures/${file}\n`)
  written.set(file, new Uint8Array(readFileSync(path)))
}

await writeCrate(written)
process.stdout.write('  wrote assets/models/crucible_crate.gltf and .bin\n')
