/**
 * `pnpm audio:bake` — synthesise `packages/client/public/audio/*.wav`.
 *
 * The sounds this game ships are **generated by this file**, not downloaded.
 * That is a licensing decision before it is an aesthetic one. A sample pack is
 * a promise about provenance made by a stranger: the pack says CC0, the pack's
 * author took one layer from somewhere else, and the repository that shipped it
 * is the one holding the problem. Mixamo is the well-known version of the trap —
 * free with an account, and its licence forbids redistributing the raw asset
 * files, so committing them to a public repository is a violation no matter how
 * the game uses them.
 *
 * Synthesising removes the question. Every sample below is computed from
 * arithmetic in this file, so the provenance is the file, the licence is ours to
 * give (CC0-1.0, recorded in `CREDITS.md`), and a reviewer can read the recipe
 * instead of trusting a hash of a zip. It is also how Quake's own sounds were
 * made in spirit: short, loud, dry, mono, and mixed to be *read* rather than
 * admired.
 *
 * ## The artifacts are committed, and this bit-reproduces them
 *
 * Same convention as `tools/bake-map.ts`: `packages/client/public/audio/*.wav`
 * is in the repository, so a Vercel build needs no bake step in front of it, and
 * `synth-audio.test.ts` re-synthesises in memory and fails if what is committed
 * is stale.
 *
 * That comparison is exact — byte for byte — which is only possible because
 * every operation here is one IEEE 754 pins down: `+`, `-`, `*`, `/`,
 * `Math.round`, and `sinRad`/`cosRad` from `@gladiator/sim`, which exist
 * precisely because `Math.sin` is implementation-approximated and differs
 * between engines. There is no `Math.exp` anywhere below; decays are written as
 * a per-sample multiply and filter coefficients as the ratios they are. The
 * simulation's reason for that rule is desync; ours is that a bake nobody can
 * reproduce is a binary blob with extra steps.
 *
 * Usage:
 *
 *     pnpm audio:bake            synthesise every sound, write the artifacts
 *     pnpm audio:bake --check    verify the committed artifacts, write nothing
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { type RngHolder, rngFloat, seedRng, sinRad } from '@gladiator/sim'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))

/** Where the WAVs are written. Vite serves `public/` at the site root. */
export const AUDIO_DIR = join(ROOT, 'packages', 'client', 'public', 'audio')

/**
 * 22050 Hz, mono, 16-bit.
 *
 * Quake shipped 11025 Hz 8-bit mono; this is one honest step up from that and
 * still a quarter the size of a 44.1 kHz stereo file. Nyquist lands at 11 kHz,
 * which keeps the spectral band HRTF uses for front/back and elevation cues
 * (roughly 4–10 kHz) intact while halving what a player downloads before their
 * first duel.
 *
 * `decodeAudioData` resamples this to the device rate once, at load, which is
 * the only place a resampling stage is allowed to happen — see
 * `packages/client/src/audio/engine.ts`.
 */
export const SAMPLE_RATE = 22050

/** Two pi, to the precision the phase accumulator needs. */
const TAU = 6.283185307179586

/* --------------------------------------------------------------------------
 * DSP primitives
 *
 * All of it mono `Float32Array` in, mono `Float32Array` out, and all of it
 * allocation-happy: this runs a dozen times in a bake, never in a frame.
 * ----------------------------------------------------------------------- */

type Signal = Float32Array

/** Sample count for a duration in seconds. */
function samples(seconds: number): number {
  return Math.round(seconds * SAMPLE_RATE)
}

/** White noise in `[-1, 1)`, from the simulation's PRNG so it is reproducible. */
function noise(count: number, seed: number): Signal {
  const holder: RngHolder = { rng: seedRng(seed) }
  const out = new Float32Array(count)
  for (let i = 0; i < count; i += 1) out[i] = rngFloat(holder) * 2 - 1
  return out
}

/**
 * An exponential decay, written as a per-sample multiply.
 *
 * `exp(-t/tau)` sampled at `1/sr` is exactly `(1 - k)^n` for the right `k`, and
 * `k = 1/(tau*sr)` is the first-order form of it — indistinguishable by ear,
 * and made of a division and a multiply rather than of `Math.exp`, which is
 * implementation-approximated and would put this bake at the mercy of a V8
 * upgrade.
 *
 * `attack` is a linear ramp, and it is never zero: a waveform that starts at
 * full amplitude on sample zero is a step, and a step is a click.
 */
function decay(count: number, tauSeconds: number, attackSeconds = 0.0015): Signal {
  const out = new Float32Array(count)
  const attack = Math.max(1, samples(attackSeconds))
  const k = 1 / (tauSeconds * SAMPLE_RATE)
  let level = 1
  for (let i = 0; i < count; i += 1) {
    const ramp = i < attack ? i / attack : 1
    out[i] = level * ramp
    level -= level * k
  }
  return out
}

/**
 * A frequency contour that glides from `fromHz` towards `toHz`.
 *
 * One-pole glide rather than a linear ramp, because a pitch that falls linearly
 * sounds like a siren and a pitch that falls exponentially sounds like a thing
 * that hit something. `tauSeconds` is how fast it gets there.
 */
function glide(count: number, fromHz: number, toHz: number, tauSeconds: number): Signal {
  const out = new Float32Array(count)
  const k = 1 / (tauSeconds * SAMPLE_RATE)
  let f = fromHz
  for (let i = 0; i < count; i += 1) {
    out[i] = f
    f += (toHz - f) * k
  }
  return out
}

/** A sine at a per-sample frequency. Phase is accumulated, never recomputed. */
function osc(freq: Signal): Signal {
  const out = new Float32Array(freq.length)
  let phase = 0
  for (let i = 0; i < freq.length; i += 1) {
    out[i] = sinRad(phase)
    phase += (TAU * (freq[i] ?? 0)) / SAMPLE_RATE
    // Keep the argument small. `sinRad` reduces the range itself, but a phase
    // that grows for a second at 3 kHz loses mantissa bits it never gets back.
    if (phase > TAU) phase -= TAU
  }
  return out
}

/** A sine at a fixed frequency. */
function tone(count: number, hz: number): Signal {
  return osc(constant(count, hz))
}

/** A constant contour, for the filters and oscillators that take one. */
function constant(count: number, value: number): Signal {
  const out = new Float32Array(count)
  out.fill(value)
  return out
}

/**
 * One-pole lowpass with a per-sample cutoff.
 *
 * `k = 2*pi*fc/sr`, clamped at 1 — the first-order form again, for the same
 * reason `decay` uses one. Cascade two of them where a 6 dB/octave slope is not
 * enough to get a noise burst out of the way.
 */
function lowpass(input: Signal, cutoff: Signal): Signal {
  const out = new Float32Array(input.length)
  let y = 0
  for (let i = 0; i < input.length; i += 1) {
    const k = Math.min(1, (TAU * (cutoff[i] ?? 0)) / SAMPLE_RATE)
    y += ((input[i] ?? 0) - y) * k
    out[i] = y
  }
  return out
}

/** One-pole highpass: the input minus its lowpass. */
function highpass(input: Signal, cutoffHz: number): Signal {
  const low = lowpass(input, constant(input.length, cutoffHz))
  const out = new Float32Array(input.length)
  for (let i = 0; i < input.length; i += 1) out[i] = (input[i] ?? 0) - (low[i] ?? 0)
  return out
}

/**
 * RBJ constant-skirt bandpass, coefficients recomputed per sample so the centre
 * frequency can sweep. Q above about 8 rings, which is what the railgun wants
 * and what a footstep very much does not.
 */
function bandpass(input: Signal, centre: Signal, q: number): Signal {
  const out = new Float32Array(input.length)
  let x1 = 0
  let x2 = 0
  let y1 = 0
  let y2 = 0
  for (let i = 0; i < input.length; i += 1) {
    const w0 = (TAU * (centre[i] ?? 0)) / SAMPLE_RATE
    const sinW = sinRad(w0)
    // cos(w) as sin(w + pi/2) keeps the whole file on one trig implementation.
    const cosW = sinRad(w0 + 1.5707963267948966)
    const alpha = sinW / (2 * q)
    const a0 = 1 + alpha
    const b0 = alpha / a0
    const b2 = -alpha / a0
    const a1 = (-2 * cosW) / a0
    const a2 = (1 - alpha) / a0
    const x0 = input[i] ?? 0
    const y0 = b0 * x0 + b2 * x2 - a1 * y1 - a2 * y2
    x2 = x1
    x1 = x0
    y2 = y1
    y1 = y0
    out[i] = y0
  }
  return out
}

/** Elementwise product — an envelope applied to a source. */
function shape(signal: Signal, envelope: Signal): Signal {
  const out = new Float32Array(signal.length)
  for (let i = 0; i < signal.length; i += 1) out[i] = (signal[i] ?? 0) * (envelope[i] ?? 0)
  return out
}

/** Add `source * gain` into `target` at `offset` samples. */
function mixInto(target: Signal, source: Signal, gain: number, offset = 0): Signal {
  for (let i = 0; i < source.length; i += 1) {
    const at = i + offset
    if (at >= target.length) break
    target[at] = (target[at] ?? 0) + (source[i] ?? 0) * gain
  }
  return target
}

/**
 * Rational soft clip: `x*d / (1 + |x*d|)`.
 *
 * Saturation is what makes a synthesised blast sound like it was recorded too
 * loud rather than like a sine wave. Rational rather than `tanh` for the same
 * reason as everything else here — division is exact, `Math.tanh` is not
 * specified to be.
 */
function saturate(signal: Signal, drive: number): Signal {
  const out = new Float32Array(signal.length)
  for (let i = 0; i < signal.length; i += 1) {
    const x = (signal[i] ?? 0) * drive
    out[i] = x / (1 + Math.abs(x))
  }
  return out
}

/** Scale so the loudest sample sits at `peak`. Silence is left alone. */
function normalise(signal: Signal, peak: number): Signal {
  let worst = 0
  for (const sample of signal) {
    const magnitude = Math.abs(sample)
    if (magnitude > worst) worst = magnitude
  }
  if (worst === 0) return signal
  const gain = peak / worst
  for (let i = 0; i < signal.length; i += 1) signal[i] = (signal[i] ?? 0) * gain
  return signal
}

/**
 * Ramp the last few milliseconds to zero.
 *
 * A buffer that ends mid-cycle is a discontinuity when the voice stops, and a
 * discontinuity at 22 kHz is a click that sounds like a bug in the mixer.
 */
function declick(signal: Signal, fadeSeconds = 0.006): Signal {
  const fade = Math.min(signal.length, samples(fadeSeconds))
  for (let i = 0; i < fade; i += 1) {
    signal[signal.length - 1 - i] = (signal[signal.length - 1 - i] ?? 0) * (i / fade)
  }
  return signal
}

/** A silent canvas of `seconds` to mix into. */
function canvas(seconds: number): Signal {
  return new Float32Array(samples(seconds))
}

/* --------------------------------------------------------------------------
 * The sounds
 *
 * Every recipe is deliberately three or four layers and no more: a body that
 * carries the pitch, a transient that carries the attack, and a tail that
 * carries the size. More layers make a prettier sound and a muddier one, and in
 * a duel these are heard through gunfire, at distance, under a rocket.
 * ----------------------------------------------------------------------- */

/**
 * The rocket launcher. A dry, low thump with a blast of air behind it.
 *
 * The pitch drop is fast (20 ms) and deep (180 Hz to 45 Hz) because that is the
 * cue that says "something heavy left the tube" rather than "a gun went off".
 */
function rocketFire(): Signal {
  const seconds = 0.55
  const count = samples(seconds)
  const out = canvas(seconds)

  const body = shape(osc(glide(count, 180, 45, 0.02)), decay(count, 0.09))
  const blast = shape(
    bandpass(noise(count, 0x5a17c0de), glide(count, 2600, 700, 0.08), 0.7),
    decay(count, 0.12),
  )
  const air = shape(lowpass(noise(count, 0x1f2e3d4c), constant(count, 1200)), decay(count, 0.25))

  mixInto(out, body, 1)
  mixInto(out, blast, 0.85)
  mixInto(out, air, 0.28)
  return declick(normalise(saturate(out, 1.4), 0.92))
}

/**
 * The railgun. Bright, electric, and over quickly, with a ring that hangs.
 *
 * Two sweeps a fifth apart rather than one: a single swept sine reads as a
 * cartoon laser, and the beating between two makes it read as energy. The
 * high-Q ring is the part a player actually recognises across a room.
 */
function railFire(): Signal {
  const seconds = 0.8
  const count = samples(seconds)
  const out = canvas(seconds)

  const zap = shape(osc(glide(count, 3200, 520, 0.05)), decay(count, 0.16))
  const detune = shape(osc(glide(count, 4805, 790, 0.05)), decay(count, 0.13))
  const ring = shape(
    bandpass(noise(count, 0x0badf00d), constant(count, 2100), 14),
    decay(count, 0.28, 0.004),
  )
  const spark = shape(highpass(noise(count, 0x7e57c0de), 3000), decay(count, 0.02))

  mixInto(out, zap, 0.9)
  mixInto(out, detune, 0.45)
  mixInto(out, ring, 0.6)
  mixInto(out, spark, 0.5)
  return declick(normalise(saturate(out, 1.2), 0.9))
}

/**
 * The explosion. The loudest thing in the game, and the one whose *tail* is the
 * information: how long the rumble lasts is how a player judges how close it
 * was, after the transient has already clipped their ears.
 */
function explosion(): Signal {
  const seconds = 1.3
  const count = samples(seconds)
  const out = canvas(seconds)

  const crackCutoff = glide(count, 6000, 200, 0.25)
  const crack = shape(
    lowpass(lowpass(noise(count, 0xdeadbeef), crackCutoff), crackCutoff),
    decay(count, 0.3),
  )
  const boom = shape(osc(glide(count, 70, 38, 0.08)), decay(count, 0.35))
  const rumble = shape(
    lowpass(noise(count, 0xc0ffee11), constant(count, 160)),
    decay(count, 0.6, 0.05),
  )

  mixInto(out, crack, 0.9)
  mixInto(out, boom, 1)
  mixInto(out, rumble, 0.55)
  // 0.97 rather than 1.0: `decodeAudioData` resamples this to the device rate,
  // and a resampler's reconstruction overshoots between samples. A file that
  // peaks at full scale is a file that clips after resampling.
  return declick(normalise(saturate(out, 1.6), 0.97), 0.05)
}

/**
 * A footstep. Ninety milliseconds, and the only sound here that plays four
 * times a second — so it is filtered narrow on purpose, to sit in a band the
 * weapons are not using and not fatigue anyone.
 *
 * Two variants, alternated by `cues.ts`, because one footstep sample played
 * repeatedly is a machine gun rather than a person running.
 */
function footstep(seed: number, centreHz: number): Signal {
  const seconds = 0.09
  const count = samples(seconds)
  const out = canvas(seconds)

  const scuff = shape(bandpass(noise(count, seed), constant(count, centreHz), 1.2), decay(count, 0.02))
  const thud = shape(osc(glide(count, 150, 90, 0.01)), decay(count, 0.03))

  // The scuff carries the step and the thud only weights it: a footstep mixed
  // the other way round is a heartbeat, and four of them a second is a horror
  // film rather than an opponent running.
  mixInto(out, scuff, 1)
  mixInto(out, thud, 0.3)
  return declick(normalise(out, 0.7), 0.004)
}

/** Landing: a footstep with weight behind it and a longer body. */
function land(): Signal {
  const seconds = 0.3
  const count = samples(seconds)
  const out = canvas(seconds)

  const thump = shape(osc(glide(count, 120, 55, 0.02)), decay(count, 0.09))
  const scuff = shape(bandpass(noise(count, 0x1a2b3c4d), constant(count, 900), 0.8), decay(count, 0.05))
  const body = shape(lowpass(noise(count, 0x44556677), constant(count, 300)), decay(count, 0.12))

  mixInto(out, thump, 1)
  mixInto(out, scuff, 0.5)
  mixInto(out, body, 0.35)
  return declick(normalise(saturate(out, 1.2), 0.85))
}

/**
 * Hit confirmation. Two rising blips, 110 ms end to end.
 *
 * It has to be *instantly* separable from every other sound in the mix, which
 * is why it is the only pure-tone sound in the set and why it rises: nothing
 * else in an arena rises. It goes down the feedback bus, never the world one —
 * a hit confirmation attenuated by distance is a hit confirmation you miss at
 * exactly the range where you needed to know.
 */
function hit(): Signal {
  const seconds = 0.11
  const count = samples(seconds)
  const out = canvas(seconds)

  const first = samples(0.045)
  const second = count - first
  mixInto(out, shape(tone(first, 1500), decay(first, 0.03, 0.001)), 1, 0)
  mixInto(out, shape(tone(second, 2250), decay(second, 0.035, 0.001)), 1, first)

  return declick(normalise(saturate(out, 1.1), 0.8), 0.004)
}

/** Damage taken. Low, blunt and unpleasant — the opposite of {@link hit}. */
function damage(): Signal {
  const seconds = 0.35
  const count = samples(seconds)
  const out = canvas(seconds)

  const crunch = shape(bandpass(noise(count, 0x9e3779b9), glide(count, 900, 260, 0.06), 1.1), decay(count, 0.12))
  const groan = shape(osc(glide(count, 160, 80, 0.05)), decay(count, 0.15))

  mixInto(out, crunch, 1)
  mixInto(out, groan, 0.7)
  return declick(normalise(saturate(out, 2), 0.85))
}

/** Round start: three rising tones. The only "announcer" this game has. */
function roundStart(): Signal {
  const out = canvas(0.9)

  const step = samples(0.18)
  const length = samples(0.22)
  const pitches = [600, 800, 1200]
  for (const [index, hz] of pitches.entries()) {
    const envelope = decay(length, index === 2 ? 0.16 : 0.07, 0.004)
    mixInto(out, shape(tone(length, hz), envelope), 0.9, step * index)
    // A quiet octave above keeps it from sounding like a phone menu.
    mixInto(out, shape(tone(length, hz * 2), envelope), 0.25, step * index)
  }
  return declick(normalise(saturate(out, 1.05), 0.8))
}

/** Round end: the same shape, falling, with air going out of the room. */
function roundEnd(): Signal {
  const seconds = 1.1
  const count = samples(seconds)
  const out = canvas(seconds)

  const length = samples(0.5)
  mixInto(out, shape(tone(length, 900), decay(length, 0.14, 0.006)), 0.9, 0)
  mixInto(out, shape(tone(length, 450), decay(length, 0.14, 0.006)), 0.3, 0)
  mixInto(out, shape(osc(glide(length, 600, 300, 0.2)), decay(length, 0.3, 0.006)), 0.8, samples(0.3))
  mixInto(
    out,
    shape(lowpass(noise(count, 0x2f6a9d1b), glide(count, 2000, 300, 0.4)), decay(count, 0.45, 0.08)),
    0.35,
  )
  return declick(normalise(saturate(out, 1.05), 0.8), 0.08)
}

/** Every sound this game ships, and the file each one is written to. */
export const RECIPES: ReadonlyArray<{ readonly file: string; readonly render: () => Signal }> = [
  { file: 'rocket-fire.wav', render: rocketFire },
  { file: 'rail-fire.wav', render: railFire },
  { file: 'explosion.wav', render: explosion },
  { file: 'footstep-a.wav', render: () => footstep(0x13579bdf, 1100) },
  { file: 'footstep-b.wav', render: () => footstep(0x2468ace0, 1350) },
  { file: 'land.wav', render: land },
  { file: 'hit.wav', render: hit },
  { file: 'damage.wav', render: damage },
  { file: 'round-start.wav', render: roundStart },
  { file: 'round-end.wav', render: roundEnd },
]

/* --------------------------------------------------------------------------
 * WAV
 * ----------------------------------------------------------------------- */

/** Mono 16-bit PCM, the one format every browser decodes without argument. */
export function encodeWav(signal: Signal, sampleRate = SAMPLE_RATE): Uint8Array {
  const bytes = new Uint8Array(44 + signal.length * 2)
  const view = new DataView(bytes.buffer)
  const ascii = (offset: number, text: string) => {
    for (let i = 0; i < text.length; i += 1) view.setUint8(offset + i, text.charCodeAt(i))
  }

  ascii(0, 'RIFF')
  view.setUint32(4, 36 + signal.length * 2, true)
  ascii(8, 'WAVE')
  ascii(12, 'fmt ')
  view.setUint32(16, 16, true) // PCM header length
  view.setUint16(20, 1, true) // PCM
  view.setUint16(22, 1, true) // mono
  view.setUint32(24, sampleRate, true)
  view.setUint32(28, sampleRate * 2, true) // byte rate
  view.setUint16(32, 2, true) // block align
  view.setUint16(34, 16, true) // bits per sample
  ascii(36, 'data')
  view.setUint32(40, signal.length * 2, true)

  for (let i = 0; i < signal.length; i += 1) {
    const clamped = Math.max(-1, Math.min(1, signal[i] ?? 0))
    // 32767 rather than 32768 on the negative side too: the asymmetry costs
    // 0.0001 dB and makes the encode its own inverse under `-x`.
    view.setInt16(44 + i * 2, Math.round(clamped * 32767), true)
  }
  return bytes
}

/** Synthesise everything, in memory. The half a test can drive. */
export function synthesiseAll(): Map<string, Uint8Array> {
  const out = new Map<string, Uint8Array>()
  for (const recipe of RECIPES) out.set(recipe.file, encodeWav(recipe.render()))
  return out
}

/* --------------------------------------------------------------------------
 * The command
 * ----------------------------------------------------------------------- */

function formatBytes(count: number): string {
  return `${(count / 1024).toFixed(1)} KiB`
}

function main(): void {
  const check = process.argv.includes('--check')
  const rendered = synthesiseAll()

  if (!check) mkdirSync(AUDIO_DIR, { recursive: true })

  const stale: string[] = []
  let total = 0

  for (const [file, bytes] of rendered) {
    const path = join(AUDIO_DIR, file)
    total += bytes.length

    if (check) {
      if (!existsSync(path)) {
        stale.push(`${file}: missing`)
        continue
      }
      const committed = new Uint8Array(readFileSync(path))
      if (committed.length !== bytes.length) {
        stale.push(`${file}: ${committed.length} bytes committed, ${bytes.length} synthesised`)
        continue
      }
      const differing = countDiffering(committed, bytes)
      if (differing > 0) stale.push(`${file}: ${differing} bytes differ`)
      continue
    }

    writeFileSync(path, bytes)
    console.log(`  ${file.padEnd(20)} ${formatBytes(bytes.length).padStart(10)}`)
  }

  // A file in the directory that no recipe produces is either a leftover or an
  // asset someone dropped in by hand — and an asset nobody can reproduce is
  // exactly what this bake exists to prevent.
  if (existsSync(AUDIO_DIR)) {
    for (const file of readdirSync(AUDIO_DIR)) {
      if (!rendered.has(file)) stale.push(`${file}: in ${AUDIO_DIR} but no recipe produces it`)
    }
  }

  if (check) {
    if (stale.length > 0) {
      console.error('audio:bake --check failed — the committed WAVs are not what this file makes:')
      for (const line of stale) console.error(`  - ${line}`)
      console.error('\nRe-bake with: pnpm audio:bake')
      process.exit(1)
    }
    console.log(`audio: ${rendered.size} sounds, ${formatBytes(total)}, committed artifacts match`)
    return
  }

  if (stale.length > 0) {
    console.error('audio: files in the output directory that no recipe produces:')
    for (const line of stale) console.error(`  - ${line}`)
    process.exit(1)
  }
  console.log(`audio: ${rendered.size} sounds, ${formatBytes(total)} total`)
}

/** How many bytes of two equal-length buffers differ. */
export function countDiffering(a: Uint8Array, b: Uint8Array): number {
  let differing = 0
  for (let i = 0; i < a.length; i += 1) if (a[i] !== b[i]) differing += 1
  return differing
}

// `tsx tools/synth-audio.ts` runs it; an import (the test) does not.
if (process.argv[1] !== undefined && process.argv[1].endsWith('synth-audio.ts')) main()
